# Generated by Django 5.2 on 2025-04-21 16:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('client', models.CharField(max_length=100, verbose_name='Заказчик')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершен')], max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Штрих-код')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Единица измерения')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращение')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичные'), ('credit', 'Отсрочка платежа')], max_length=20, verbose_name='Способ оплаты')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Штрих-код')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('construction_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.constructionobject', verbose_name='Объект')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Запись материала',
                'verbose_name_plural': 'Записи материалов',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='Ед. изм.'),
        ),
    ]
