# Generated by Django 5.2 on 2025-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_constructionobject_material_unit_materialrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrecord',
            name='material',
            field=models.CharField(max_length=200, verbose_name='Материал'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
