# Generated by Django 5.2 on 2025-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_constructionobject_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('address', models.TextField(verbose_name='Адрес склада')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.AddField(
            model_name='materialrecord',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='materialrecord',
            name='operation_type',
            field=models.CharField(choices=[('income', 'Приход'), ('outcome', 'Расход'), ('transfer', 'Перемещение')], default='income', max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AddField(
            model_name='materialrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='Склад'),
        ),
    ]
