# Generated by Django 5.2 on 2025-04-21 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_warehouse_materialrecord_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrecord',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.constructionobject', verbose_name='Объект'),
        ),
    ]
