# Generated by Django 5.2 on 2025-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_materialrecord_payment_type_historyodwarehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrecord',
            name='from_Warehouse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='это поле из склада?'),
        ),
    ]
