# Generated by Django 5.2 on 2025-04-25 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_materialrecord_from_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyodwarehouse',
            options={'ordering': ['-datetime'], 'verbose_name': 'История склада', 'verbose_name_plural': 'История склада'},
        ),
        migrations.AddField(
            model_name='materialrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичные')], max_length=20, verbose_name='Способ оплаты')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Штрих-код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('construction_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.constructionobject', verbose_name='Объект')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='Ед. изм.')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
            },
        ),
    ]
