# Generated by Django 5.2 on 2025-04-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_historyodwarehouse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObjectOfWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Строительный объект',
                'verbose_name_plural': 'Строительный объекты',
            },
        ),
    ]
