# Generated by Django 5.2 on 2025-04-25 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_constructionobjectofwarehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionobjectofwarehouse',
            options={'verbose_name': 'Строительный объект склада', 'verbose_name_plural': 'Строительный объекты склада'},
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время'),
        ),
    ]
