# Generated by Django 5.2 on 2025-04-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_storagelocation_construction_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='from_Warehouse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='это поле из склада?'),
        ),
    ]
