# Generated by Django 5.2 on 2025-04-25 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_storagelocation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='core.warehouse', verbose_name='Склад'),
        ),
    ]
