# Generated by Django 5.2 on 2025-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_storagelocation_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название места'),
        ),
    ]
