# Generated by Django 5.2 on 2025-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_storagelocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrecord',
            name='is_operations',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='эта операция?'),
        ),
        migrations.AddField(
            model_name='materialrecord',
            name='object_is_operations',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='имя операции'),
        ),
    ]
