# Generated by Django 5.2 on 2025-04-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_storagelocation_construction_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.constructionobjectofwarehouse', verbose_name='Объект'),
        ),
    ]
